### ISSUE TITLE
Discrepancies in Album Scrobble Counts

### ISSUE THREAD

**Issue by kbuterba** [neilmenon/lastfm-with-friends#61]
![album_scrobble_count](https://user-images.githubusercontent.com/64853910/130332127-a02af990-35fa-451d-a49b-df3c07b1af6f.PNG)

**Comment by neilmenon** [comment]
@kbuterba most likely not going to fix this in the near future, even though there shouldn't be a discrepancy. The call to get all tracks in an album for "who knows" is pretty expensive, but it's only one album. For charts, that would be 100 calls of this type. Will try and think of a more efficient way to make these match up.
